server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 915123

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.cloud.entity

# 在服务中心注册
eureka:
  instance:
    instance-id: payment-8001
    prefer-ip-address: true
  client:
    register-with-eureka: true # 将自己注册进Eureka Server
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/    #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址


